In [1]:
import os

if os.path.basename(os.getcwd()) == 'notebooks':
    os.chdir('..')
    
os.getcwd()

'/home/zack/personal/prediction_market_tools'

In [2]:
import pandas as pd

In [3]:
p = pd.read_csv('data/raw/predsnprices.csv')

In [4]:
from src import expected_value

In [5]:
p, latest_p = expected_value.prep_prices_csv(p)

/home/zack/personal/prediction_market_tools/src/expected_value.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  latest_p["buyYes"] = latest_p.myBet > latest_p.yesPrice
/home/zack/miniconda3/envs/preds/lib/python3.9/site-packages/pandas/core/frame.py:3636: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
/home/zack/personal/prediction_market_tools/src/expected_value.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  latest_p["expected_value"] = (latest_p.myp * latest_p.mktq) - (

In [6]:
latest_p

,symbol,date,yesPrice,noPrice,myBet,purchase,qty,buyYes,mktp,myp,mktq,myq,expected_value
6,VOHC-001,2021-09-14,0.36,0.66,0.25,n,98.0,False,0.66,0.75,0.34,0.25,0.09
7,NYSCHL-001,2021-09-14,0.84,0.17,0.90,y,125.0,True,0.84,0.90,0.16,0.10,0.06
9,CASE-038,2021-09-14,0.07,0.95,0.05,NaN,NaN,False,0.95,0.95,0.05,0.05,0.00
14,CASE-039,2021-09-15,0.06,NaN,0.05,NaN,NaN,False,NaN,0.95,NaN,0.05,NaN
16,CASE-040,2021-09-16,0.98,0.03,1.00,NaN,NaN,True,0.98,1.00,0.02,0.00,0.02
18,WKCASE-004,2021-09-16,0.99,0.02,1.00,NaN,NaN,True,0.99,1.00,0.01,0.00,0.01
20,CASE-041,2021-09-17,0.50,0.50,0.70,NaN,NaN,True,0.50,0.70,0.50,0.30,0.20
21,CASE-042,2021-09-17,0.34,0.66,0.25,NaN,NaN,False,0.66,0.75,0.34,0.25,0.09
22,CASE-042,2021-09-17,0.81,0.21,0.75,NaN,NaN,False,0.21,0.25,0.79,0.75,0.04
23,CASE-042,2021-09-17,NaN,0.65,0.90,NaN,NaN,False,0.65,0.10,0.35,0.90,-0.55
25,LCASE-001,2021-09-20,0.09,0.96,0.10,NaN,NaN,True,0.09,0.10,0.91,0.90,0.01
26,LCASE-002,2021-09-20,0.13,0.90,0.15,NaN,NaN,True,0.13,0.15,0.87,0.85,0.02
27,FLUV-001,2021-09-20,0.19,0.96,0.10,NaN,NaN,False,0.96,0.90,0.04,0.10,-0.06
28,RAINNYC-009,2021-09-20,NaN,0.85,0.10,NaN,NaN,False,0.85,0.90,0.15,0.10,0.05
29,CASE-043,2021-09-20,0.05,NaN,0.01,NaN,NaN,False,NaN,0.99,NaN,0.01,NaN
30,NHIGH-047,2021-09-20,0.01,0.01,0.55,NaN,NaN,True,0.01,0.55,0.99,0.45,0.54

In [7]:
from src import kalshi

In [8]:
k = kalshi.Kalshi()

In [9]:
k.login()

In [10]:
markets = k.select_markets_by_ticker(latest_p.symbol)
markets

,id,title,category,tags,ranged_group_name,image_url,min_tick_size,settle_details,settlement_sources,ticker_name,...,yes_ask,last_price,previous_yes_bid,previous_yes_ask,previous_price,volume,recent_volume,open_interest,result,no_ask
0,2f485e17-27ac-4337-ad04-d63a9fc578ad,Will the CDC identify a variant of high conseq...,COVID-19,"[COVID-19, Variant]",The CDC’s SARS-CoV-2 Variant Classifications.,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,If the CDC identifies a variant of high conseq...,[{'url': 'https://www.cdc.gov/coronavirus/2019...,VOHC-001,...,0.30,0.26,0.29,0.30,0.30,2734,178,2392,,0.80
1,c549ccac-ad50-4f41-a1d1-771745ee97e5,Will New York public schools remain fully open...,COVID-19,"[New York, Education]",The reopening plans of the New York City publi...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,If New York City public schools remain fully o...,"[{'url': 'https://www.schools.nyc.gov/', 'name...",NYSCHL-001,...,1.00,0.84,0.83,1.00,0.84,5088,0,2896,,1.00
2,11e5e5bf-d342-48ee-b1d0-cbf11ed34992,"Will there be over 160,000 new COVID-19 cases ...",COVID-19,"[COVID, Cases]",The number of new cases of COVID-19 published ...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,If the number of new cases of COVID-19 reporte...,[{'url': 'https://covid.cdc.gov/covid-data-tra...,CASE-038,...,0.01,0.01,0.00,0.01,0.01,8532,3464,5864,no,1.00
3,32f3aaa7-dc08-47f4-9b43-c5c47b47ae1b,"Will there be over 150,000 new COVID-19 cases ...",COVID-19,"[COVID, Cases]",The number of new cases of COVID-19 published ...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,If the number of new cases of COVID-19 reporte...,[{'url': 'https://covid.cdc.gov/covid-data-tra...,CASE-039,...,0.01,0.01,0.00,0.01,0.01,7638,4200,3982,no,1.00
4,b9689b80-9810-4bbd-b48a-8c637be5f056,"Will there be over 140,000 new COVID-19 cases ...",COVID-19,"[COVID, Cases]",The number of new cases of COVID-19 published ...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,If the number of new cases of COVID-19 reporte...,[{'url': 'https://covid.cdc.gov/covid-data-tra...,CASE-040,...,1.00,0.98,0.99,1.00,0.98,5748,0,1574,yes,0.01
5,bbfa850b-811e-4a68-b3b1-6ccd5b6ac9d3,"Will there be over 980,000 new COVID-19 cases ...",COVID-19,"[COVID, Cases, Weekly]",The total sum of reported new COVID-19 cases p...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,If the total number of reported new COVID-19 c...,[{'url': 'https://covid.cdc.gov/covid-data-tra...,WKCASE-004,...,1.00,0.99,0.99,1.00,0.99,15978,0,11516,yes,0.01
6,257bebb5-1641-4a27-882d-bab2bfe06b5f,"Will there be over 130,000 new COVID-19 cases ...",COVID-19,"[COVID, Cases]",The number of new cases of COVID-19 published ...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,If the number of new cases of COVID-19 reporte...,[{'url': 'https://covid.cdc.gov/covid-data-tra...,CASE-041,...,1.00,0.99,0.99,1.00,0.99,4572,4572,4572,yes,0.01
7,df5ada35-1129-43e2-a775-e91acc172d8f,"Will there be over 140,000 new COVID-19 cases ...",COVID-19,"[COVID, Cases]",The number of new cases of COVID-19 published ...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,If the number of new cases of COVID-19 reporte...,[{'url': 'https://covid.cdc.gov/covid-data-tra...,CASE-042,...,1.00,0.76,0.99,1.00,0.76,580,0,556,yes,0.01
8,df5ada35-1129-43e2-a775-e91acc172d8f,"Will there be over 140,000 new COVID-19 cases ...",COVID-19,"[COVID, Cases]",The number of new cases of COVID-19 published ...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,If the number of new cases of COVID-19 reporte...,[{'url': 'https://covid.cdc.gov/covid-data-tra...,CASE-042,...,1.00,0.76,0.99,1.00,0.76,580,0,556,yes,0.01
9,df5ada35-1129-43e2-a775-e91acc172d8f,"Will there be over 140,000 new COVID-19 cases ...",COVID-19,"[COVID, Cases]",The number of new cases of COVID-19 published ...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,If the number of new cases of COVID-19 reporte...,[{'url': 'https://covid.cdc.gov/covid-data-tra...,CASE-042,...,1.00,0.76,0.99,1.00,0.76,580,0,556,yes,0.01
10,654e1b59-9979-403d-af50-35434a440e1b,"Will there be a day with at least 200,000 new ...",COVID-19,"[COVID-19, Cases, Minimum]",The reported number of new cases of COVID-19 p...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,If the number of reported new COVID-19 cases i...,[{'url': 'https://covid.cdc.gov/covid-data-tra...,LCASE-001,...,0.05,0.05,0.03,0.09,0.03,132640,2990,22128,,0.97
11,4dd57553-dd3c-4308-a284-9b319c5cce60,"Will there be a day with at least 200,000 new ...",COVID-19,"[COVID-19, Cases, Minimum]",The reported number of new cases of COVID-19 p...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,If the number of reported new COVID-19 cases i...,[{'url': 'https://covid.cdc.gov/covid-data-tra...,LCASE-002,...,0.12,0.13,0.10,0.13,0.13,600,600,600,,0.90
12,aa34fbc6-7514-484d-af16-888fd70e949c,Will the FDA give emergency authorization for ...,COVID-19,"[Covid-19, fluvoxamine]",Press announcements issued by the FDA Newsroom.,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,If the FDA issues a press announcement authori...,[{'url': 'https://www.fda.gov/news-events/fda-...,FLUV-001,...,0.19,0.17,0.01,0.17,0.15,2650,472,1178,,0.96
13,1459b052-de7f-4336-aacf-081bba01c54b,Will it rain in New York City on Tuesday?,Climate and Weather,[Rain],The number of inches of precipitation recorded...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,If the number of inches of precipitation recor...,[{'url': 'https://www.weather.gov/wrh/Climate?...,RAINNYC-009,...,1.00,0.15,0.15,1.00,0.00,100,100,100,,0.85
14,b18273c3-1dab-4dcc-aa55-96caf7ba42e6,"Will there be over 140,000 new COVID-19 cases ...",COVID-19,"[COVID, Cases]",The number of new cases of COVID-19 published ...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,If the number of new cases of COVID-19 reporte...,[{'url': 'https://covid.cdc.gov/covid-data-tra...,CASE-043,...,0.01,0.00,0.00,0.05,0.00,0,0,0,,1.00
15,bf6e42be-352a-4697-9ffb-be4371dd3ef5,Will the high in New York City be over 76° on ...,Climate and Weather,"[Climate, Temperature, New York, Daily]",The highest temperature recorded in Central Pa...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,If the highest temperature recorded in Central...,[{'url': 'https://www.weather.gov/wrh/Climate?...,NHIGH-047,...,1.00,0.50,0.01,0.49,0.49,126,126,126,,0.65

In [11]:
bets = latest_p[['symbol','date','myBet']].merge(markets, how='left', left_on='symbol', right_on='ticker_name')

In [12]:
bets = bets[bets.status == 'active']

In [13]:
bets.columns

Index(['symbol', 'date', 'myBet', 'id', 'title', 'category', 'tags',
       'ranged_group_name', 'image_url', 'min_tick_size', 'settle_details',
       'settlement_sources', 'ticker_name', 'create_date', 'list_date',
       'open_date', 'close_date', 'expiration_date', 'status',
       'expiration_value', 'description_context', 'description_case_yes',
       'description_case_no', 'yes_bid', 'yes_ask', 'last_price',
       'previous_yes_bid', 'previous_yes_ask', 'previous_price', 'volume',
       'recent_volume', 'open_interest', 'result', 'no_ask'],
      dtype='object')

In [14]:
bets

,symbol,date,myBet,id,title,category,tags,ranged_group_name,image_url,min_tick_size,...,yes_ask,last_price,previous_yes_bid,previous_yes_ask,previous_price,volume,recent_volume,open_interest,result,no_ask
0,VOHC-001,2021-09-14,0.25,2f485e17-27ac-4337-ad04-d63a9fc578ad,Will the CDC identify a variant of high conseq...,COVID-19,"[COVID-19, Variant]",The CDC’s SARS-CoV-2 Variant Classifications.,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,...,0.30,0.26,0.29,0.30,0.30,2734,178,2392,,0.80
1,NYSCHL-001,2021-09-14,0.90,c549ccac-ad50-4f41-a1d1-771745ee97e5,Will New York public schools remain fully open...,COVID-19,"[New York, Education]",The reopening plans of the New York City publi...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,...,1.00,0.84,0.83,1.00,0.84,5088,0,2896,,1.00
16,LCASE-001,2021-09-20,0.10,654e1b59-9979-403d-af50-35434a440e1b,"Will there be a day with at least 200,000 new ...",COVID-19,"[COVID-19, Cases, Minimum]",The reported number of new cases of COVID-19 p...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,...,0.05,0.05,0.03,0.09,0.03,132640,2990,22128,,0.97
17,LCASE-002,2021-09-20,0.15,4dd57553-dd3c-4308-a284-9b319c5cce60,"Will there be a day with at least 200,000 new ...",COVID-19,"[COVID-19, Cases, Minimum]",The reported number of new cases of COVID-19 p...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,...,0.12,0.13,0.10,0.13,0.13,600,600,600,,0.90
18,FLUV-001,2021-09-20,0.10,aa34fbc6-7514-484d-af16-888fd70e949c,Will the FDA give emergency authorization for ...,COVID-19,"[Covid-19, fluvoxamine]",Press announcements issued by the FDA Newsroom.,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,...,0.19,0.17,0.01,0.17,0.15,2650,472,1178,,0.96
19,RAINNYC-009,2021-09-20,0.10,1459b052-de7f-4336-aacf-081bba01c54b,Will it rain in New York City on Tuesday?,Climate and Weather,[Rain],The number of inches of precipitation recorded...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,...,1.00,0.15,0.15,1.00,0.00,100,100,100,,0.85
20,CASE-043,2021-09-20,0.01,b18273c3-1dab-4dcc-aa55-96caf7ba42e6,"Will there be over 140,000 new COVID-19 cases ...",COVID-19,"[COVID, Cases]",The number of new cases of COVID-19 published ...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,...,0.01,0.00,0.00,0.05,0.00,0,0,0,,1.00
21,NHIGH-047,2021-09-20,0.55,bf6e42be-352a-4697-9ffb-be4371dd3ef5,Will the high in New York City be over 76° on ...,Climate and Weather,"[Climate, Temperature, New York, Daily]",The highest temperature recorded in Central Pa...,https://kalshi-public-images.s3.us-east-2.amaz...,$0.01,...,1.00,0.50,0.01,0.49,0.49,126,126,126,,0.65

In [17]:
bets[['symbol', 'yes_bid', 'no_ask', 'yes_ask', 'last_price', 'myBet']]

         symbol  yes_bid  no_ask  yes_ask  last_price  myBet
0      VOHC-001     0.20    0.80     0.30        0.26   0.25
1    NYSCHL-001     0.00    1.00     1.00        0.84   0.90
16    LCASE-001     0.03    0.97     0.05        0.05   0.10
17    LCASE-002     0.10    0.90     0.12        0.13   0.15
18     FLUV-001     0.04    0.96     0.19        0.17   0.10
19  RAINNYC-009     0.15    0.85     1.00        0.15   0.10
20     CASE-043     0.00    1.00     0.01        0.00   0.01
21    NHIGH-047     0.35    0.65     1.00        0.50   0.55

In [23]:
bets['buyYes'] = bets.myBet >= bets.yes_ask
bets['buyNo'] = bets.myBet <= bets.yes_bid
bets['buyable'] = bets.buyYes | bets.buyNo

In [24]:
bets[['symbol', 'yes_bid', 'no_ask', 'yes_ask', 'last_price', 'myBet', 'buyYes', 'buyNo', 'buyable']]

,symbol,yes_bid,no_ask,yes_ask,last_price,myBet,buyYes,buyNo,buyable
0,VOHC-001,0.20,0.80,0.30,0.26,0.25,False,False,False
1,NYSCHL-001,0.00,1.00,1.00,0.84,0.90,False,False,False
16,LCASE-001,0.03,0.97,0.05,0.05,0.10,True,False,True
17,LCASE-002,0.10,0.90,0.12,0.13,0.15,True,False,True
18,FLUV-001,0.04,0.96,0.19,0.17,0.10,False,False,False
19,RAINNYC-009,0.15,0.85,1.00,0.15,0.10,False,True,True
20,CASE-043,0.00,1.00,0.01,0.00,0.01,True,False,True
21,NHIGH-047,0.35,0.65,1.00,0.50,0.55,False,False,False

In [25]:
bets = bets[bets.buyable]
bets['myp'] = bets.myBet.where(bets.buyYes, 1 - bets.myBet)  
bets['mktp'] = bets.yes_ask.where(bets.buyYes, 1 - bets.yes_bid)
bets[["mktq", "myq"]] = 1 - bets[["mktp", "myp"]]
bets["expected_value"] = (bets.myp * bets.mktq) - (
    bets.myq * bets.mktp
)

/tmp/ipykernel_5622/2935630589.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bets['myp'] = bets.myBet.where(bets.buyYes, 1 - bets.myBet)
/tmp/ipykernel_5622/2935630589.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bets['mktp'] = bets.yes_ask.where(bets.buyYes, 1 - bets.yes_bid)
/home/zack/miniconda3/envs/preds/lib/python3.9/site-packages/pandas/core/frame.py:3636: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
/tmp/ipykernel_5622/2935630589.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bets["expected_value"] = (bets.myp * bets.mktq) - (

In [26]:
bets[['symbol', 'yes_bid', 'no_ask', 'yes_ask', 'last_price', 'myBet', 'buyYes', 'buyNo', 'buyable', 'expected_value']]

,symbol,yes_bid,no_ask,yes_ask,last_price,myBet,buyYes,buyNo,buyable,expected_value
16,LCASE-001,0.03,0.97,0.05,0.05,0.10,True,False,True,0.05
17,LCASE-002,0.10,0.90,0.12,0.13,0.15,True,False,True,0.03
19,RAINNYC-009,0.15,0.85,1.00,0.15,0.10,False,True,True,0.05
20,CASE-043,0.00,1.00,0.01,0.00,0.01,True,False,True,0.00

In [ ]:
# todo: check order book?